apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crc-ingress
  labels:
    app: crc-nginx
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    service.beta.kubernetes.io/azure-dns-label-name: imkumpy
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts: 
        - imkumpy.com
      secretName: imkumpy-tls-cert
  defaultBackend:
    service:
      name: crc-service
      port:
        number: 80
  rules:
  - host: imkumpy.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: crc-service
            port: 
              number: 80
