apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crc-ingress
  labels:
    app: crc-nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts: 
        - imkumpy.com
      secretName: imkumpy-tls-cert
  ingressClassName: nginx
  rules:
    - host: imkumpy.com
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: crc-service
              port: 
                number: 80
