apiVersion: apps/v1
kind: Deployment
metadata:
  name: crc-nginx
spec:
  selector:
    matchLabels:
      app: crc-nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: crc-nginx
    spec:
      containers:
        - name: crc-nginx
          image: nginx:1.7.8
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 50Mi
              cpu: 250m
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          volumeMounts:
            - mountPath: /usr/share/nginx/html/
              name: nginx-volume
      volumes:
        - name: nginx-volume
          configMap:
            name: crc-nginx-configmap
